--SELECT * FROM jordan_playoffs;

----DATA DICTIONARY--
--Playoff game
--Date (yyyy-mm-dd)
--Series name (EC = Eastern Conference, WC = Western Conference, 1 = First Round, S = Conference Semifinals, F = Conference Finals, FIN = NBA Finals)
--Series game number
--Player's team
--Opponent
--Win (W) or Loss (L) with the point differential in parenthesis
--Minutes played
--Field goals made
--Field goals attempted
--Field goal percentage
--3-point field goals made
--3-point field goals attempted
--3-point field goal percentage
--Free throws made
--Free throws attempted
--Free throw percentage
--Offensive rebounds
--Defensive rebounds
--Total rebounds
--Assists
--Steals
--Blocks
--Turnovers
--Points scored
--Statistical measure of a player's productivity for a single game
--Statistical measure of a player's impact on the game, represented by the difference between their team's total scoring versus their opponent's when the player is in the game

-- --COLUMN DESCRIPTION--
--Data Description--
--exec sp_columns JORDAN_PLAYOFFS;

----nos of rows--
--select count(*) Nos_of_Rows
--from JORDAN_PLAYOFFS;

----nos of columns--
--select count(*)columns
--from information_schema.columns
--where table_name = 'JORDAN_PLAYOFFS';

----CHECKING FOR NULL VALUES IN EACH COLUMNS
--SELECT COUNT(*) AS NULL_VALUES FROM JORDAN_PLAYOFFS 
--WHERE ftp  IS NULL;

--SELECT COUNT(*) AS NULL_VALUES FROM JORDAN_PLAYOFFS 
--WHERE threep  IS NULL;

--SELECT COUNT(*) AS NULL_VALUES FROM JORDAN_PLAYOFFS
--WHERE plus_minus  IS NULL;

----CHECKING FOR DUPLICATES--
--SELECT GAME, COUNT(GAME) AS COUNT
--from JORDAN_PLAYOFFS
--group by GAME
--having COUNT(GAME) > 1;

----ADDITION OF NEW COLUMNS--
--ALTER TABLE JORDAN_PLAYOFFS
--ALTER COLUMN MATCH_RESULT VARCHAR(50);

--ALTER TABLE JORDAN_PLAYOFFS
--ADD POINT_DIFF INT;

--ALTER TABLE JORDAN_PLAYOFFS
--ADD RESULT VARCHAR(50);

--ALTER TABLE JORDAN_PLAYOFFS
--ADD SERIES_NAME VARCHAR(100);

----DROP COLUMNS--
--ALTER TABLE JORDAN_PLAYOFFS
--DROP COLUMN MATCH_RESULT,PLUS_MINUS,
--	THREE_POINT_GOALS_PERCENT;
		

----EXPUNGING PARENTHESIS FROM THE FIGURES IN MATCH_RESULT COLUMN--
--UPDATE JORDAN_PLAYOFFS
--SET MATCH_RESULT = (SELECT REPLACE(REPLACE(MATCH_RESULT,')',' '),'(',' ')
--			);
----POPULATING NEW COLUMNS AND FORMATTING THE FIELDS OF PREXISTING COLUMNS--
--UPDATE JORDAN_PLAYOFFS
--SET RESULT = (SELECT SUBSTRING(MATCH_RESULT,1,1) 
--				WHERE RESULT IS NULL);

--UPDATE JORDAN_PLAYOFFS
--SET POINT_DIFF = (SELECT LTRIM(SUBSTRING(MATCH_RESULT,3,4))
--					WHERE POINT_DIFF IS NULL);

--UPDATE JORDAN_PLAYOFFS
--SET RESULT = (SELECT CASE 
--						WHEN RESULT = 'W' THEN 'Win'
--						ELSE 'Lost'
--						END);

--UPDATE JORDAN_PLAYOFFS
--SET GAME_SCORE = (SELECT ROUND(GAME_SCORE,2));

--UPDATE JORDAN_PLAYOFFS
--SET FIELD_GOALS_PERCENT = (SELECT ROUND(FIELD_GOALS_PERCENT,2));

--UPDATE JORDAN_PLAYOFFS
--SET FREE_THROW_PERCENT = (SELECT ROUND(FREE_THROW_PERCENT,2));

--UPDATE JORDAN_PLAYOFFS
--SET THREE_POINT_GOALS_PERCENT = (SELECT ROUND(THREE_POINT_GOALS_PERCENT,2));

--UPDATE JORDAN_PLAYOFFS
--SET TEAM = (SELECT CASE WHEN TEAM = 'WAS' THEN 'Washington Wizard'
--					WHEN TEAM = 'CHI' THEN 'Chicago Bull'
--			END);

--UPDATE JORDAN_PLAYOFFS
--SET SERIES_NAME = (SELECT CASE WHEN SERIES = 'EC1' THEN 'Eastern Conference (First Round)'
--					WHEN SERIES = 'ECS' THEN 'Eastern Conference (Semi-Finals)'
--					WHEN SERIES = 'ECF' THEN 'Eastern Conference (Finals)'
--					WHEN SERIES = 'FIN' THEN 'NBA FINALS'
--			END);

----REFORMATTING COLUMN HEADERS--
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.game','GAME','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.date','DATE','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.series','SERIES','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.series_game','SERIES_GAME','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.team','TEAM','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.opp','OPPONENT','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.result','MATCH_RESULT','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.mp','MINUTES_PLAYED','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.fg','FIELD_GOALS','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.fga','FIELD_GOALS_ATTEMPTED','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.fgp','FIELD_GOALS_PERCENT','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.three','THREE_POINT_FIELD_GOALS','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.threeatt','THREE_POINT_ATTEMPTED','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.threep','THREE_POINT_GOALS_PERCENT','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.ft','FREE_THROW_MADE','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.fta','FREE_THROW_ATTEMPTED','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.ftp','FREE_THROW_PERCENT','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.orb','OFFENSIVE_REBOUND','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.drb','DEFENSIVE_REBOUND','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.trb','TOTAL_REBOUND','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.ast','ASSIST','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.stl','STEAL','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.blk','BLOCKS','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.tov','TURN_OVER','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.pts','POINTS','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.game_score','GAME_SCORE','COLUMN';
--EXEC SP_RENAME 'JORDAN_PLAYOFFS.plus_minus','PLUS_MINUS','COLUMN';
--EXEC SP_RENAME 'J_PLAYOFFS.NAME','OPPONENT','COLUMN';

----INSERTING THE AGGREGATED TABLE INTO A NEW TABLE 'JORDAN_PLAYOFFS'--
--SELECT * 
--INTO J_PLAYOFFS
--FROM(
--	SELECT GAME, DATE, SERIES, SERIES_NAME, SERIES_GAME, J.TEAM, OPPONENT AS CODE_NAME,N.NAME, MINUTES_PLAYED, RESULT, FIELD_GOALS,FIELD_GOALS_ATTEMPTED,
--		FIELD_GOALS_PERCENT,THREE_POINT_FIELD_GOALS, THREE_POINT_ATTEMPTED,THREE_POINT_GOALS_PERCENT, FREE_THROW_MADE, FREE_THROW_ATTEMPTED,FREE_THROW_PERCENT,
--		OFFENSIVE_REBOUND, DEFENSIVE_REBOUND,TOTAL_REBOUND,ASSIST, STEAL,BLOCKS,TURN_OVER,POINTS,POINT_DIFF, GAME_SCORE
--	FROM JORDAN_PLAYOFFS J
--	JOIN NBA_TEAMS N 
--	ON J.OPPONENT = N.TEAM)A;

--EFFICIENCY--

--NBA titles won--
--SELECT COUNT(*) AS TITLES FROM J_PLAYOFFS
--WHERE SERIES_NAME = 'NBA FINALS' AND  RESULT = 'WIN';

--total series played--
--SELECT COUNT(SERIES) AS SERIES_PLAYED
--FROM J_PLAYOFFS;

----games played per series-
--SELECT SERIES_NAME, COUNT(SERIES) AS SERIES_PLAYED,
--		SUM(FIELD_GOALS) AS GOALS,
--		COUNT(CASE WHEN RESULT = 'WIN' THEN 1 END) AS WIN,
--		COUNT(CASE WHEN RESULT = 'LOST' THEN 1 END) AS LOSS
--FROM J_PLAYOFFS
--GROUP BY SERIES_NAME
--ORDER BY SERIES_NAME ASC;

----total points won--
--SELECT SUM(POINTS) AS TOTAL_POINTS
--FROM J_PLAYOFFS;

----Average Points Per Game--
--SELECT AVG(POINTS) AS AVG_POINT 
--FROM J_PLAYOFFS;

----Total Goals Scored and Attempts--
--SELECT SUM(FIELD_GOALS) AS PLAYOFFS_GOALS
--FROM J_PLAYOFFS;

--SELECT SUM(FIELD_GOALS_ATTEMPTED) AS GOAL_ATTEMPTS
--FROM J_PLAYOFFS;

----Goals to Expected Goals Ratio--
--SELECT ROUND(AVG(FIELD_GOALS_PERCENT),2) * 100 AS G_xG_RATIO
--FROM J_PLAYOFFS;

----Goals Scored per Series--
--SELECT SERIES_NAME, SUM(FIELD_GOALS) AS GOALS,
--		SUM(FIELD_GOALS_ATTEMPTED) AS GOAL_ATTEMPTS,
--		ROUND(AVG(FIELD_GOALS_PERCENT),2) AS G_xG_RATIO
--FROM J_PLAYOFFS
--GROUP BY SERIES_NAME
--ORDER BY SERIES_NAME ASC;

----Scoring consistency--
--SELECT COUNT(*) AS MATCHES_WITHOUT_GOAL
--FROM J_PLAYOFFS
--WHERE FIELD_GOALS = 0;

--Wins and Loss against Opponents--
--SELECT OPPONENT, COUNT(OPPONENT) AS MATCHES_PLAYED,
--		COUNT(CASE WHEN RESULT = 'WIN' THEN 1 END) AS WINS,
--		COUNT(CASE WHEN RESULT = 'LOST' THEN 1 END) AS LOSS
--FROM J_PLAYOFFS
--GROUP BY OPPONENT
--ORDER BY WINS DESC;

----Total Free Throw Made--
--SELECT SUM(FREE_THROW_MADE) AS TOTAL_FREE_THROW
--FROM J_PLAYOFFS;

----Total Free Throw Attempted--
--SELECT SUM(FREE_THROW_ATTEMPTED) AS TOTAL_FREE_THROW
--FROM J_PLAYOFFS;

----Free Throw Ratio--
--SELECT ROUND(SUM(FREE_THROW_PERCENT)/10,2) AS FREE_THROW_RATIO
--FROM J_PLAYOFFS;

--PLAY MAKING AND PASSING--

--Total Career Assist--
--SELECT SUM(ASSIST) AS PLAYOFFS_ASSISTS
--FROM J_PLAYOFFS;

--Average Assist per Game--
--SELECT AVG(ASSIST) as AVERAGE_ASSIST_PER_GAME 
--FROM J_PLAYOFFS;

----Total Assist per Series--
--SELECT SERIES_NAME, SUM(ASSIST) AS TOTAL_ASSIST
--FROM J_PLAYOFFS
--GROUP BY SERIES_NAME 
--ORDER BY SERIES_NAME ASC;

----Assist to Turnover Ratio--
--SELECT SUM(ASSIST)/SUM(TURN_OVER) AS ASSIST_TURNOVER_RATIO
--FROM J_PLAYOFFS;

----DEFENSIVE IMPACT--

----Rebounding--
--SELECT SERIES_NAME,
--		SUM(OFFENSIVE_REBOUND) AS OFFENSIVE_REBOUND, 
--		SUM(DEFENSIVE_REBOUND) AS DEFENSIVE_REBOUND,
--		(SUM(OFFENSIVE_REBOUND) + SUM(DEFENSIVE_REBOUND)) AS TOTAL_REBOUND
--FROM J_PLAYOFFS
--GROUP BY SERIES_NAME
--ORDER BY SERIES_NAME ASC;

----Steal per Game and Total Steal--
--SELECT SUM(STEAL) AS TOTAL_STEAL
--FROM J_PLAYOFFS;

----Average Steals and Total Steals per Season
--SELECT SERIES_NAME  AS SERIES, COUNT(SERIES) AS MATCHES, AVG(STEAL) AS AVG_STEAL, SUM(STEAL) AS TOTAL_STEAL
--FROM J_PLAYOFFS
--GROUP BY SERIES_NAME  
--ORDER BY SERIES_NAME  ASC;

----Block per Game and Total Blocks--
--SELECT SUM(BLOCKS) AS TOTAL_BLOCKS
--FROM J_PLAYOFFS;

--SELECT * FROM J_PLAYOFFS
